// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rarkmceyquiwyzenvyjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcmttY2V5cXVpd3l6ZW52eWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTI5OTUsImV4cCI6MjA3MTg2ODk5NX0.Vh8b-4StE7UFw8evcSWjbG2AyD-0mWFtZ-PbEp2FgJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});